[package]
name = "inference_server"
version = "0.1.0"
edition = "2024"

[dependencies]
onnxruntime = {version = "0.0.14"}
polars = { version = "=0.44.2", features = ["ndarray", "csv"] }
rayon = "1.10.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
ndarray = "0.15.1"
