[package]
name = "infer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.35", features = ["derive" ] }
ndarray = "0.16.1"
ort = { version = "=2.0.0-rc.9", features = ["load-dynamic"] }
polars = { version = "0.46.0", features = ["ndarray", "csv"] }
